name: continuous-integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Update
      run: sudo apt-get update
    - name: Install Dependencies
      run: |
        sudo apt-get install --assume-yes build-essential ninja-build cmake clang-10
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCMAKE_CXX_COMPILER=clang++-10 ..
    - name: Build
      run: cd build && ninja
    - name: Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: exquisite
        path: build/exquisite
